zeroc: | 
    Ice.ThreadPool.Client.SizeMax = 10                              
    Ice.ThreadPool.Server.SizeMax = 10                              
    Ice.MessageSizeMax = 1000000   

seed: 
    pubIP: &seedPubIP 172.17.2.130 
    gossipPort: &seedGossipPort 25005 
    rpcPort: &seedRpcPort 25004 
    httpPort: &seedHttpPort 25003 
    shardSize: &shardSize 1 
    shardNodeSize: &shardNodeSize 4 
    static: &static 1 
    whitelist: &whitelist 
        - 172.17.2.46
        - 172.17.2.62
        - 172.17.2.63
        - 172.17.2.104
        - 172.17.2.118
        - 172.17.2.119
        - 172.17.2.117
        - 172.17.2.120
        - 172.17.2.123
        - 172.17.2.126
        - 172.17.2.127
        - 172.17.2.128
        - 172.17.2.130

fullnode:
    pubIP: 172.17.2.130 
    gossipPort: 25025 
    rpcPort: 25024 
    httpPort: 25023 
    prefix: 1 
    shardSize: *shardSize
    shardNodeSize: *shardNodeSize
    static: *static
    whitelist: *whitelist

localfullnode2: 
    pubIP: 172.17.2.130 
    gossipPort: 35791 
    rpcPort: 35792 
    httpPort: 35793 
    prefix: &lfnPrefix 0 
    whitelist: *whitelist

    seedPubIP: *seedPubIP 
    seedGossipPort: *seedGossipPort 
    seedRpcPort: *seedRpcPort 
    seedHttpPort: *seedHttpPort 

    dbConnectionDescriptors:    
        -
            url: "spring.datasource.url0_0=jdbc:mysql://localhost:3306/main0_0?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8" 
            un: "spring.datasource.username0_0=root" 
            pw: "spring.datasource.password0_0=eiR2qeNso0vpEm5pwznjZwQjO4AXGpru3vqFTaEte3GpEpeZu2RtA0kwyWPg6s7cipxxuv7beC4jN4hY20DQ7Au61ZEdXSnhy2TCIJNHrMsY9PFusPQOrtkLwm6MUb7XSNLM6uTDR51mVtEqsCplh7UxNk3OF9LNhn8ruH4ECXY=" 
        -
            url: "spring.datasource.url0_1=jdbc:mysql://localhost:3306/main0_1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8"
            un: "spring.datasource.username0_1=root"
            pw: "spring.datasource.password0_1=eiR2qeNso0vpEm5pwznjZwQjO4AXGpru3vqFTaEte3GpEpeZu2RtA0kwyWPg6s7cipxxuv7beC4jN4hY20DQ7Au61ZEdXSnhy2TCIJNHrMsY9PFusPQOrtkLwm6MUb7XSNLM6uTDR51mVtEqsCplh7UxNk3OF9LNhn8ruH4ECXY="
        -
            url: "spring.datasource.url0_2=jdbc:mysql://localhost:3306/main0_2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8"
            un: "spring.datasource.username0_2=root"
            pw: "spring.datasource.password0_2=eiR2qeNso0vpEm5pwznjZwQjO4AXGpru3vqFTaEte3GpEpeZu2RtA0kwyWPg6s7cipxxuv7beC4jN4hY20DQ7Au61ZEdXSnhy2TCIJNHrMsY9PFusPQOrtkLwm6MUb7XSNLM6uTDR51mVtEqsCplh7UxNk3OF9LNhn8ruH4ECXY="
        -
            url: "spring.datasource.url0_3=jdbc:mysql://localhost:3306/main0_3?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8"
            un: "spring.datasource.username0_3=root"
            pw: "spring.datasource.password0_3=eiR2qeNso0vpEm5pwznjZwQjO4AXGpru3vqFTaEte3GpEpeZu2RtA0kwyWPg6s7cipxxuv7beC4jN4hY20DQ7Au61ZEdXSnhy2TCIJNHrMsY9PFusPQOrtkLwm6MUb7XSNLM6uTDR51mVtEqsCplh7UxNk3OF9LNhn8ruH4ECXY="

p2pcluster:                 
    icport: &icport 33010 
  
env: 
    p2pcluster.icport: *icport
    database.reset: false
    test.prefix: *lfnPrefix
    io.netty.leakDetectiontionLevel: advanced
